config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :sentences do
    resources :blips, only: [:create, :destroy, :show]
  end

  

  root to: "sentences#index"

  # USER AUTH ROUTES

  resources :users

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  get "/history" => "users#history"
  get "/sentences/:id/stats" => "sentences#stats"



end

app/models/sentence.rb
class Sentence < ActiveRecord::Base

  #BLIPS RELATION
  has_many :blips, dependent: :destroy

  #TAGS RELATION
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags, allow_destroy: true

  #VALIDATIONS
  validates :body, presence: true
  validates :body, uniqueness: true


  #return total blips of this perticular body for this sentence
  def word_total(id)
    Blip.where(sentence_id: id).count
  end

  def other_responses(id)
    self.group(:created_on).count
    #self.blips_count.to_f / 2
  end

   def blip_count(sentence_id, body)
    Blip.where(sentence_id: sentence_id, body: body).count
  end 


end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController

  before_action :find_sentence, only: [:show]



  respond_to :json, :js

  def new
    @sentence = Sentence.new
  end

  def create
    @sentence = Sentence.new sentence_params
    #@sentence.user = current_user
    if @sentence.save
      flash[:success] = "Sentence successfully created."
      redirect_to sentences_path
    else
      flash.now[:alert] = "Sentence was not created!"
      render :new
    end
  end

  def index
    if current_user
      @sentences = Sentence.all.order("created_at ASC") - current_user.sentences
      #@sentences = Sentence.include(:blips).all.order("created_at DESC") - current_user.sentences

    else
      @sentences = Sentence.all.order("created_at ASC")
    end
  end

  def show
    @sentence = Sentence.find(params[:id])
    count = @sentence.blips.group(:body).distinct.count
    percent = count.each {|k, v| count[k] = (v / (@sentence.blips_count.to_f / 2) * 100).round(2) }
    statistics = percent.sort_by { |k, v| v }.reverse[0..3].each { |k, v| puts "#{k}: #{v}" }
    render json: statistics
  end

  def stats
    #refactor this
    @sentence = Sentence.find(params[:id])
    count = @sentence.blips.group(:body).distinct.count
    percent = count.each {|k, v| count[k] = (v / (@sentence.blips_count.to_f / 2) * 100).round(2) }
    @statistics = percent.sort_by { |k, v| v }.reverse[0..9].each { |k, v| puts "#{k}: #{v}" }

    final_output = []
    User.uniq.pluck(:country).each do |country|
      all_blips_for_country = []
      User.where(country: country).each do |user|
        user.blips.each do |blip|
          all_blips_for_country << blip
        end
      end

      output = Hash.new(0)
      all_blips_for_country.each do |blip|
        output[blip.body] += 1
      end
      final_set = output.sort_by{ |k,v| v }
      final_set.reverse!
      if final_set[0]
        tmp = final_set[0]
        final_output << [country, tmp[0]]
      end
    end

    @final_output = final_output
  end

  def destroy
    @sentence.destroy
    flash[:success] = "Sentence successfully deleted."
    redirect_to root_path
  end

  def edit

  end


  private

  def sentence_params
    params.require(:sentence).permit(:body, { tag_ids:[] })
  end

  def find_sentence
    @sentence = Sentence.find params[:id]
  end

end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/sentences/_form.html.erb
  <div class="form-group">
    <%= form_for @sentence do |f| %>
    <%= f.text_field :body, class: "form-control", placeholder: "Sentence" %><br>
    <br>
    <hr>
    <%= f.submit class: "btn btn-default" %>
    <%= button_tag "Reset", type: :reset %>
    <% end %>
  </div>

app/views/sentences/_stats.html.erb
<div class="stats-box">
  <div class="stats-header">Pulses for:</div>
  <div class="stats-sentence"><%= @sentence.body.gsub("*", "_?_").html_safe  %></div>
  <div class="stats-share"><a href="#"><%= image_tag ('fb-share.gif'), width: 30, height: 30 %></a>&nbsp;<a href="#"><%= image_tag ('twitter-logo.gif'), width: 30, height: 30 %></a></div>
  <hr>
  
  <div class="col-md-12 stats-container">
    <div class="stats-subheader col-md-4"><span class="stats-subheader-stat"><%= @sentence.blips.count %></span><br> total blips</div>
    <div class="stats-subheader col-md-4"><span class="stats-subheader-stat">10</span><br> countries</div>
    <div class="stats-subheader col-md-4"><span class="stats-subheader-stat">12</span><br> cities</div>
  </div>
  <br>
  <p class="chart-header">Top Pulse per Country</p>
<div class="chart"><%= geo_chart [["United States",44],["Germany",23],["Brazil",22], ["Canada", 89], ["France", 32], ["Congo", 48], ["China", 100], ["Russia", 21], ["Argentina", 40], ["Sweden", 20], ["Kenya", 40]], library: {backgroundColor: "transparent", width: 500}, colors: ["#001412", "#004640", "#139e92", "#139e93", "#80cdc6", "#006d63", "#00d0c4", "#d0f3ef", "#d0f4ef", "#d0f2ef"] %></div>
  <hr>
  <p class="chart-header">The Most Popular Pulses</p>
  <div class="chart-pie">
    <%= pie_chart @statistics, library: {backgroundColor: "transparent", width: 600}, colors: ["#001412", "#004640", "#139e92", "#139e93", "#80cdc6", "#006d63", "#00d0c4", "#d0f3ef", "#d0f4ef", "#d0f2ef"] %>
  </div>
  <hr>
  <p class="chart-header">By Gender</p>
  <div class="col-sm-12">
    <div class="chart-pies col-sm-6"><p class="chart-header-sub">Gents</p>
      <%= pie_chart [["Money",44],["Cars",23],["Sex",22], ["Career", 89], ["Wealth", 32], ["Love", 48]], library: {backgroundColor: "transparent", width: 320}, colors: ["#001412", "#004640", "#139e92", "#139e93", "#80cdc6", "#006d63", "#00d0c4", "#d0f3ef", "#d0f4ef", "#d0f2ef"] %>
    </div>
    <div class="chart-pies col-sm-6"><p class="chart-header-sub">Ladies</p>
      <%= pie_chart @statistics, library: {backgroundColor: "transparent", width: 320}, colors: ["#001412", "#004640", "#139e92", "#139e93", "#80cdc6", "#006d63", "#00d0c4", "#d0f3ef", "#d0f4ef", "#d0f2ef"] %>
    </div>
  </div>
</div>

app/views/sentences/edit.html.erb
<h1>Edit Sentence</h1>

<%= render "form" %>

app/views/sentences/index.html.erb
<div class="main-logo">one pulse</div>
<div class="header col-md-12">
  <div class="main-subheader col-md-4">&nbsp;</div>
  <div class="main-subheader col-md-4">hello, world. what's on your mind?</div>
  <div class="main-menu col-md-4"><span class="nav-text-links">
    <% if !current_user %>
    <a rel="leanModal" name="login" href="#login">
      <span class="nav-text-links-pre"> 
    [+]</span>login </a>
    <a rel="leanModal" name="signup" href="#signup"><span class="nav-text-links-pre"> [+]</span>signup </a></span>
    <span class="nav-text-links">
    <a rel="leanModal" name="how" href="#how">
    <span class="nav-text-links-pre"> [+]</span>how this works </a></span>
    <% else %>
    <!-- <span>Welcome back <%= current_user.name ||= current_user.email %></span> -->
    <span class="nav-text-links">
    <a rel="leanModal" name="submit" href="#submit">
    <span class="nav-text-links-pre"> [+]</span>submit </a></span>
    <%= link_to '<span class="nav-text-links-pre">
    [+]</span>history'.html_safe, history_path %>
    
    <%= link_to '<span class="nav-text-links-pre"> [+]</span>profile'.html_safe, edit_user_path(current_user) %>
    <%= link_to '<span class="nav-text-links-pre">
     [+]</span>logout'.html_safe, log_out_path %>
    <% end %>
    
    
  </div>
</div>
<%= react_component 'IndexPage',
{sentences: @sentences.map { |s| SentenceSerializer.new(s, root: false) }} %>
<div class="filters">
  <%= image_tag "world_filter_icon.gif", height: 40, width: 40, class: "world-filter" %>
  <%= image_tag "filter_point_03_03.gif", height: 24, width: 24, class: "bubble-point" %>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/sentences/new.html.erb
<h1>Create sentence</h1>

<%= render "form" %>

app/views/sentences/stats.js.erb
$(".modal-body").html("<%= j render 'stats' %>");